### ISSUE TITLE
asignacion de botones erronea

### ISSUE THREAD

**Issue by elaguuu** [FThompson/NetflixController#13]
no se si a alguien mas le paso porque si yo preciono un boton (ejemplo:O) me lo cuenta como otro boton (ej:X)

**Comment by FThompson** [comment]
Hey, thanks for reporting this issue. Can you answer a few questions?
* Does this issue occur for any buttons other than O and X?
* Does the extension work as expected other than the swapped buttons?
* What is your controller (e.g. Sony PS3, Sony PS4, non-Sony controller) and operating system (e.g. Windows 10, macOS Catalina)?

This extension uses a standard gamepad layout, and I verified that the O/X icons match the expected button indices. I wonder if there's a hardware or software compatibility issue that results in this problem.

Thanks!

---

(Spanish translation courtesy of Google Translate)

Hola, gracias por informar de este problema. ¿Puede responder algunas preguntas?
* ¿Este problema ocurre con otros botones que no sean O y X?
* ¿La extensión funciona como se esperaba aparte de los botones intercambiados?
* ¿Cuál es su controlador (por ejemplo, Sony PS3, Sony PS4, controlador que no es de Sony) y sistema operativo (por ejemplo, Windows 10, macOS Catalina)?

Esta extensión usa un diseño de gamepad estándar y verifiqué que los íconos O / X coinciden con los índices de botones esperados. Me pregunto si hay un problema de compatibilidad de hardware o software que provoque este problema.

¡Gracias!

**Comment by elaguuu** [comment]
gracias por su atencion.
el problema sucede con todos los botones menos el círculo y las flechas
también están invertidas(cruceta derecha me lo detecta como cruceta arriba
y cruceta izquierda como cruceta abajo.)
la extensión detecta la palanca derecha pero aunque tenga los botone mal
configurados tampoco funcionan
uso un gamepad genérico con cable con diseño de PS2 y uso ubuntu linux
use X y O como ejemplo ficticio ya que solo O funciona bien
espero que esa información le sirva, gracias.

**Comment by FThompson** [comment]
Thanks for the info! Nice to see someone using Ubuntu :) I tested the extension on Ubuntu 18.10 with an Xbox One controller and it worked as expected. I wonder if it's a driver issue that causes the wrong buttons to be detected for your controller. Does this controller work as expected for other applications on Ubuntu?

Can you test your controller on https://gamepad-tester.com/ and check if it detects the correct buttons? If the detected buttons don't match the pressed buttons, then this confirms that it's either a driver issue or maybe a compatibility issue between Google Chrome and Ubuntu. You could see if using different gamepad drivers resolves the issue.

---

(Spanish translation courtesy of Google Translate)

Gracias por la info! Es bueno ver a alguien usando Ubuntu :) Probé la extensión en Ubuntu 18.10 con un controlador Xbox One y funcionó como se esperaba. Me pregunto si es un problema de controlador que hace que se detecten los botones incorrectos para su controlador. ¿Este controlador funciona como se esperaba para otras aplicaciones en Ubuntu?

¿Puedes probar tu mando en https://gamepad-tester.com/ y comprobar si detecta los botones correctos? Si los botones detectados no coinciden con los botones presionados, esto confirma que es un problema de controlador o tal vez un problema de compatibilidad entre Google Chrome y Ubuntu. Puede ver si el uso de diferentes controladores de gamepad resuelve el problema.

**Comment by elaguuu** [comment]
hola, perdon por la tardanza en contestar
no supe como usar la página que me mandó 😅
pero lo probé en una ya instalada por defecto en ubuntu "jstest-gtk" .ahí
me funciona todo correctamente

**Comment by FThompson** [comment]
The gamepadtester website shows the raw gamepad input data. Plug in your controller and press buttons to show the data. If your controller has a "standard" configuration, the website also shows a gamepad with your inputs drawn live on it. If the gamepad drawing didn't appear, then your controller isn't reporting the "standard" configuration (and this is why the buttons are wrong for NetflixController). The "standard" configuration has 4 axes and 17 buttons. Another common configuration has 8 axes and 10 buttons. I suspect that Chrome detects your controller as the latter. On my Ubuntu laptop, for comparison, Chrome detects my Xbox One controller as the "standard" configuration, but Firefox detects it as the non-standard 8/10 configuration.

Unfortunately, there's not much else I can do to help, because the issue lies between the gamepad, the operating system, and the browser. I could add support for remapping in the extension, but that would take a considerable amount of effort (and I'm not sure how soon I would have time do complete this). Maybe try another driver like `xboxdrv` or `xpad`?

---

(Spanish translation courtesy of Google Translate)

El sitio web de gamepadtester muestra los datos de entrada sin procesar del gamepad. Conecte su controlador y presione los botones para mostrar los datos. Si su controlador tiene una configuración "estándar", el sitio web también muestra un gamepad con sus entradas dibujadas en vivo en él. Si el dibujo del gamepad no apareció, entonces su controlador no informa la configuración "estándar" (y esta es la razón por la que los botones no son correctos para NetflixController). La configuración "estándar" tiene 4 ejes y 17 botones. Otra configuración común tiene 8 ejes y 10 botones. Sospecho que Chrome detecta su controlador como este último. En mi computadora portátil Ubuntu, a modo de comparación, Chrome detecta mi controlador Xbox One como la configuración "estándar", pero Firefox lo detecta como la configuración 8/10 no estándar.

Desafortunadamente, no hay mucho más que pueda hacer para ayudar, porque el problema radica entre el gamepad, el sistema operativo y el navegador. Podría agregar soporte para reasignación en la extensión, pero eso requeriría una cantidad considerable de esfuerzo (y no estoy seguro de qué tan pronto tendré tiempo para completar esto). ¿Quizás probar con otro controlador como `xboxdrv` o` xpad`?

**Comment by FThompson** [comment]
Unable to reproduce issue. Likely an issue of hardware/driver compatibility, where the gamepad isn't reported as a standard layout gamepad.
