### ISSUE TITLE
"Netflix Controller" started debugging this browser 

### ISSUE THREAD

**Issue by danieljustus32** [FThompson/NetflixController#15]
When entering fullscreen mode, this notification appears at the top of the screen, and the only way to close it is to get up and click out of it. If I click the "Cancel" button, it seems to disable Netflix Controller completely. Any way to suppress this notification so I don't have to close it every time I go fullscreen? Awesome work on this extension by the way 🥇

**Comment by FThompson** [comment]
Hey, thanks for reporting this.

Netflix Controller uses the debugger to set the video to full screen, because Chrome doesn't normally allow extensions to set full screen mode. Previously, the extension enabled the debugger only briefly to toggle full screen, so that you wouldn't see the debugger banner. However, it looks like the latest version of Chrome keeps the banner visible to make it obvious when extensions use debugger in this way. This was a hacky fix to begin with, so I'm not surprised that I need to find an alternative.

Edit: Removed contextMenus idea, which seems to be incorrect.

**Comment by danieljustus32** [comment]
Dang, I was hoping there would be a way in Chrome to just keep the banner from ever appearing, but in that case I might look into contributing a PR for this. You're thinking of adding that permission and then creating a context menu item that sets the browser to fullscreen when a controller button is pressed?

**Comment by FThompson** [comment]
I found a much easier way to toggle full screen, which I'm surprised I didn't find before lol.

https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen

Tested and works, and doesn't require special permissions. I'll post again when the update is ready. I might also fix the broken browse page issue in this update but that's a much larger task.

**Comment by danieljustus32** [comment]
Oh awesome, thank you!

**Comment by FThompson** [comment]
Update published to the Chrome web store.

Thanks again for reporting this issue!
