### ISSUE TITLE
Virtual Keyboard for search does not work

### ISSUE THREAD

**Issue by hachikuyi** [FThompson/NetflixController#6]
![image](https://user-images.githubusercontent.com/64060621/79861471-0878e680-8407-11ea-94b0-cc4419f1df2b.png)
This is the error when I try pressing /\ on my PS4 Controller, other functions work just fine

**Comment by FThompson** [comment]
Hey, thanks for reporting this issue.

I'm unable to reproduce the issue. Could you please answer a few questions?
* On what page(s) does this issue occur?
* In what country do you reside? (Netflix shows different content in certain locales, which may cause issues because I tested the extension on the US site).

Could you also check if this issue still occurs on the latest version of the plugin, v1.0.3?

Thanks!
